services:
  - type: web
    name: subscription-service
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /login
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: cloud
