spring:
  datasource:
    url: jdbc:h2:mem:subscription;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: always
      data-locations: classpath:db/cloud-data.sql

  thymeleaf:
    cache: true

server:
  port: ${PORT:8080}
